import fitz
print("Testing template...")
doc = fitz.open("data/HEALTH AND WELLNESS GUIDE - Fillable Guide 1.pdf")
print(f"Template pages: {len(doc)}")
doc.close()
print("Testing example...")
doc = fitz.open("data/Health and wellness guide example.pdf")
print(f"Example pages: {len(doc)}")
doc.close()
print("Success")
